name: arch

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
jobs:
  build-arch:
    name: "arch"
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
    - name: Install deps
      run: "echo '[multilib]' >> /etc/pacman.conf && echo 'Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf && pacman -Syu --noconfirm git util-linux sudo fakeroot binutils autoconf automake libtool pkgconf file make && useradd -m arch && echo 'arch ALL=(ALL) NOPASSWD: ALL' | (EDITOR='tee -a' visudo)"
    - name: Generate-lib32-evdev
      if: false
      run: runuser -l arch -c "git clone https://aur.archlinux.org/lib32-check.git lib32-check && cd lib32-check && makepkg --syncdeps --noconfirm --install" && runuser -l arch -c "git clone https://aur.archlinux.org/lib32-libevdev.git lib32-libevdev && cd lib32-libevdev && makepkg --syncdeps --noconfirm --install"
    - name: Build launcher
      run: runuser -l arch -c "git clone https://aur.archlinux.org/mcpelauncher-linux-git mcpelauncher-linux-git && cd mcpelauncher-linux-git && makepkg --syncdeps --noconfirm --install" || true
    - name: Build msa
      if: false
      run: runuser -l arch -c "git clone https://aur.archlinux.org/mcpelauncher-msa-git.git mcpelauncher-msa-git && cd mcpelauncher-msa-git && makepkg --syncdeps --noconfirm --install" && runuser -l arch -c "git clone https://aur.archlinux.org/mcpelauncher-msa-ui-qt-git.git mcpelauncher-msa-ui-qt-git && cd mcpelauncher-msa-ui-qt-git && makepkg --syncdeps --noconfirm --install" || true
    - name: Build Qt launcher
      run: runuser -l arch -c "git clone https://aur.archlinux.org/mcpelauncher-ui-git.git mcpelauncher-ui-git && cd mcpelauncher-ui-git && makepkg --syncdeps --noconfirm --install" || true
    - name: Copy artifacts
      run: runuser -l arch -c "sudo mkdir -p $GITHUB_WORKSPACE/output/ && sudo cp ./*/*.pkg.tar.zst $GITHUB_WORKSPACE/output/" && cp /var/cache/pacman/pkg/protobuf*.pkg.tar.zst output/
    - uses: actions/upload-artifact@v3
      with:
        name: archpkgs
        path: output/
